import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Share2, Loader2, Copy, Check, Users } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { useToast } from "@/hooks/use-toast";

interface ShareSafeSummaryProps {
  contractId: number;
}

interface ShareSummary {
  summary: string;
  keyPoints: string[];
  concerns: string[];
  recommendation: string;
}

export function ShareSafeSummary({ contractId }: ShareSafeSummaryProps) {
  const [showSummary, setShowSummary] = useState(false);
  const [copied, setCopied] = useState(false);
  const { toast } = useToast();

  const { data: summary, isLoading, refetch } = useQuery<ShareSummary>({
    queryKey: ["/api/contracts", contractId, "share-summary"],
    enabled: false,
  });

  const handleGetSummary = async () => {
    if (summary) {
      setShowSummary(!showSummary);
      return;
    }
    setShowSummary(true);
    refetch();
  };

  const handleCopy = async () => {
    if (!summary) return;

    const text = `Contract Summary

${summary.summary}

Key Points:
${summary.keyPoints.map(p => `- ${p}`).join("\n")}

${summary.concerns.length > 0 ? `Concerns:\n${summary.concerns.map(c => `- ${c}`).join("\n")}\n\n` : ""}Recommendation: ${summary.recommendation}

(Generated by Redline IQ - Contract Analysis)`;

    await navigator.clipboard.writeText(text);
    setCopied(true);
    toast({
      title: "Copied!",
      description: "Summary copied to clipboard. Ready to share!",
    });
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-3">
      <Button
        variant="outline"
        onClick={handleGetSummary}
        disabled={isLoading}
        className="gap-2"
        data-testid="button-share-summary"
      >
        {isLoading ? (
          <Loader2 className="h-4 w-4 animate-spin" />
        ) : (
          <Share2 className="h-4 w-4" />
        )}
        {showSummary ? "Hide Summary" : "Share-Safe Summary"}
      </Button>

      {showSummary && summary && (
        <Card className="bg-muted/30" data-testid="share-summary">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-base">
              <span className="flex items-center gap-2">
                <Users className="h-4 w-4" />
                Shareable Summary
              </span>
              <Button
                variant="ghost"
                size="sm"
                onClick={handleCopy}
                className="gap-2"
                data-testid="button-copy-summary"
              >
                {copied ? (
                  <>
                    <Check className="h-3 w-3" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="h-3 w-3" />
                    Copy
                  </>
                )}
              </Button>
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm">{summary.summary}</p>

            <div>
              <h5 className="text-xs font-medium text-muted-foreground mb-2">
                Key Points:
              </h5>
              <ul className="space-y-1">
                {summary.keyPoints.map((point, i) => (
                  <li key={i} className="text-sm flex items-start gap-2">
                    <span className="text-primary">-</span>
                    {point}
                  </li>
                ))}
              </ul>
            </div>

            {summary.concerns.length > 0 && (
              <div>
                <h5 className="text-xs font-medium text-muted-foreground mb-2">
                  Worth Discussing:
                </h5>
                <div className="flex flex-wrap gap-2">
                  {summary.concerns.map((concern, i) => (
                    <Badge
                      key={i}
                      variant="outline"
                    >
                      {concern}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            <div className="pt-3 border-t">
              <p className="text-sm font-medium">{summary.recommendation}</p>
            </div>

            <p className="text-xs text-muted-foreground italic">
              Share this with your partner, parent, or friend to discuss.
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
